#!/bin/bash

#set -x

LOG=log-amoeba
if test -f log-amoeba; then

  grep  TOTAL_NODES $LOG 
  
  echo  
  
  GAMES=$(grep -c TOTAL_NODES $LOG)
  BLACK=$(grep -c winner=X $LOG)
  WHITE=$(grep -c winner=O $LOG)
  DRAW=$(grep  -c winner=D $LOG)

  echo "GAMES =" $GAMES   #$(( ($BLACK+$BLACK+$DRAW)*50/$GAMES ))% 
  echo "BLACK =" $BLACK   #$(( $BLACK*100/$GAMES ))%
  echo "WHITE =" $WHITE   #$(( $WHITE*100/$GAMES ))%
  echo "DRAW  =" $DRAW    #$(( $DRAW*100/$GAMES ))%
  echo "MOVES =" $(grep -c  Nodes $LOG)
  echo

  grep  TIME: $LOG #| tail -n 1


fi

echo
