#!/bin/bash
. log-client

if test -d "${AMOEBA_PLAYDIR}"; then
    if [[ ${AMOEBA_CLIENT} == x ]];then
        grep X amoeba*-${AMOEBA_CLIENT}* | wc -l
        grep O amoeba*-${AMOEBA_CLIENT}* | wc -l
    else
        grep O amoeba*-${AMOEBA_CLIENT}* | wc -l
        grep X amoeba*-${AMOEBA_CLIENT}* | wc -l
    fi
    sleep 2
fi


LOG=$1
if [ "$LOG" == ""  ]; then
    LOG=log${AMOEBA_CLIENT}-amoeba
fi

echo
grep Nodes $LOG  | grep X | sort -t = -k 3 -n | tail
echo
grep Nodes $LOG  | grep O | sort -t = -k 3 -n | tail
echo
grep -E 'TOTAL_NODES|TIME' $LOG 
echo


GAMES=$(grep -c TOTAL_NODES $LOG)
BLACK=$(grep -c winner=X $LOG)
WHITE=$(grep -c winner=O $LOG)
DRAW=$(grep  -c winner=D $LOG)

echo GAMES=$GAMES   $(( ($BLACK+$BLACK+$DRAW)*50/$GAMES ))% 
echo BLACK=$BLACK   $(( $BLACK*100/$GAMES ))%
echo WHITE=$WHITE   $(( $WHITE*100/$GAMES ))%
echo DRAW=$DRAW     $(( $DRAW*100/$GAMES ))%
echo MOVES=$(grep -c  Nodes $LOG)


sleep 3
