#!/bin/bash

export AMOEBA_CLIENT=o   
export AMOEBA_POWER=7.30+

#################################################################################
# ezek kellenek a szerver elleni játékhoz
#################################################################################

# az amoeba szerver IP címe
export AMOEBA_IP=localhost
export AMOEBA_PORT=4321


# mindig automatikusan játszik, 2 lehetőség:

# (1)  AMOEBA_CONTINUOUS_PLAY darab játékot játszik (előlről)
export AMOEBA_CONTINUOUS_PLAY=20

# (2)  AMOEBA_PLAYDIR-ben levő játékokat sorban betölti és folytatja
# export AMOEBA_PLAYDIR=../amoeba-plays


#################################################################################

export AMOEBA_CELLSIZE=40
export AMOEBA_COLOR=60,60,50
export AMOEBA_TIME_LIMIT=100
export AMOEBA_BLINK=1


amoeba.exe | tee -a  log-amoeba

