#!/bin/bash
cd ~/amoeba
. ~/envccc
clear

export AMOEBA_CONTINUOUS_PLAY=10
export AMOEBA_POWER_BLACK=7
export AMOEBA_POWER_WHITE=7

export AMOEBA_CELLSIZE=40
export AMOEBA_COLOR=77,66,22

amoeba.exe  -t 14  "$@" | tee log-amoeba_$$
