#!/bin/bash
cd ~/amoeba
#gc
#m
. ~/envccc
clear

export AMOEBA_CONTINUOUS_PLAY=10
export AMOEBA_POWER_BLACK=4+
export AMOEBA_POWER_WHITE=4+

export AMOEBA_CELLSIZE=44
export AMOEBA_COLOR=77,66,22

amoeba.exe  -t 12  "$@" | tee log-amoeba
