#!/bin/bash
cd ~/amoeba
. ~/envccc
clear

export AMOEBA_CONTINUOUS_PLAY=true
export AMOEBA_POWER_WHITE=7
export AMOEBA_POWER_BLACK=6

export AMOEBA_CELLSIZE=48
export AMOEBA_COLOR=77,66,22

amoeba.exe  -t 14  "$@" | tee log-amoeba
