#!/bin/bash

export AMOEBA_IP=i3x
export AMOEBA_PORT=4321
export AMOEBA_CLIENT=o
export AMOEBA_PLAYDIR=~/amoeba-plays


# AMOEBA_CONTINUOUS_PLAY=10 : magtol nem valaszol
# AMOEBA_CONTINUOUS_PLAY=0  : automatikusan valaszol (default)
# AMOEBA_CONTINUOUS_PLAY=1  : onmaga ellen jatszik (1 partit)
# AMOEBA_CONTINUOUS_PLAY=n  : onmaga ellen jatszik  n darab partit

# export AMOEBA_CONTINUOUS_PLAY=0
# export AMOEBA_POWER_BLACK=8.3+
# export AMOEBA_POWER_WHITE=8.3+
# export AMOEBA_TABLESIZE=16

 export AMOEBA_CELLSIZE=40
 export AMOEBA_COLOR=60,60,50
 export AMOEBA_TIME_LIMIT=120
 export AMOEBA_BLINK=2

amoeba $@ -p 5   | tee   log${AMOEBA_CLIENT}-amoeba

