#!/bin/bash

TOTAL=$(ls -l amoeba??-* | wc -l)
XWIN=$(grep X amoeba??-* | wc -l)
OWIN=$(grep O amoeba??-* | wc -l)
DRAW=$(($TOTAL-$XWIN-$OWIN))

echo
echo TOTAL=$TOTAL  $(( ($XWIN+$XWIN+$DRAW)*50/$TOTAL ))%
echo XWIN=$XWIN    $(( $XWIN*100/$TOTAL ))%
echo OWIN=$OWIN    $(( $OWIN*100/$TOTAL ))%
echo DRAW=$DRAW    $(( $DRAW*100/$TOTAL ))%
echo

grep Nodes log-amoeba  | sort -t = -k 2 -n | tail
echo

grep TOTAL log-amoeba  | tail
echo
    
sleep 3
